import Head from 'next/head';
import { useState } from 'react';

import { STATES } from './defs';

import { Button } from '@components/Button';
import { Container } from '@components/Container';
import { TextInput } from '@components/TextInput';

export default function Login() {
  const [selectedIndex, setSelectedIndex] = useState(0);

  const GROUP = Object.values(STATES).map((key) => {
    switch (key) {
      case STATES.SIGN_IN:
        return 'Sign In';
      case STATES.SIGN_UP:
        return 'Sign Up';
      default:
        return null;
    }
  });

  return (
    <>
      <Head>
        <title>Login</title>
        <meta content="Generated by create next app" name="description" />
        <meta content="width=device-width, initial-scale=1" name="viewport" />
        <link href="/favicon.ico" rel="icon" />
      </Head>
      <main>
        <Container
          alignCenter
          fluid
          justifyCenter
          css={{ height: '100vh', minWidth: '100vw' }}
          display="flex"
        >
          <Container
            alignCenter
            fluid
            justifyCenter
            css={{
              backgroundColor: '$accents1',
              flexWrap: 'wrap',
              gap: '12px',
              p: '$xl',
              width: '80vw',
              '@sm': { width: '50vw' },
              '@md': { width: '40vw' },
            }}
            display="inline-flex"
          >
            <Button.Group>
              {GROUP.map((val, index) => (
                <Button
                  key={val}
                  bordered={index === selectedIndex}
                  onPress={() => setSelectedIndex(index)}
                >
                  {val}
                </Button>
              ))}
            </Button.Group>

            <TextInput
              fullWidth
              primary
              required
              autoComplete="on"
              label="Email"
              placeholder="Please enter your email address"
              type="email"
            />

            <TextInput.Password
              fullWidth
              primary
              required
              label="Password"
              placeholder="Please enter your password"
              type="password"
            />

            <Button>{GROUP[selectedIndex]}</Button>
          </Container>
        </Container>
      </main>
    </>
  );
}
