import Head from 'next/head';
import { useRouter } from 'next/router';
import { useSession } from 'next-auth/react';
import { useEffect, useState } from 'react';

import { Container } from '@components/Container';
import { Page } from '@defs/journals';
import { useLoginRedirect } from '@hooks';
import { getJournalById } from '@service/api';
import { Pages } from '@templates/Pages';

export default function JournalPages() {
  const router = useRouter();
  useLoginRedirect();
  const { data } = useSession();

  const [pages, setPages] = useState<Page[]>();

  const [pageLoading, setPageLoading] = useState(true);

  useEffect(() => {
    setPageLoading(true);
    getJournalById(router.query.journalId as string)
      .then((res) => setPages(res.data.pages))
      .catch(console.error)
      .finally(() => setPageLoading(false));
  }, [data, router.query.journalId]);

  return (
    <>
      <Head>
        <title>Your Travel Journals</title>
        <meta content="Generated by create next app" name="description" />
        <meta content="width=device-width, initial-scale=1" name="viewport" />
        <link href="/favicon.ico" rel="icon" />
      </Head>
      <main>
        <Container
          alignCenter
          fluid
          row
          css={{
            height: '100vh',
            minWidth: '100vw',
            p: '$md',
            gridTemplateColumns: 'repeat(auto-fit, minmax(100px, 1fr))',
            gridGap: '$xs $xs',
            '@xs': {
              gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))',
              p: '$xl',
              gridGap: '$xl $xl',
            },
            '@md': {
              gridTemplateColumns: 'repeat(auto-fit, minmax(300px, 1fr))',
              p: '$xl',
              gridGap: '$xl $xl',
            },
          }}
          display="grid"
          justify="flex-start"
        >
          {pages?.map((page) => (
            <Pages key={page.pageId} page={page} />
          ))}
          {!pageLoading && <Pages />}
        </Container>
      </main>
    </>
  );
}
